import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, Building2, Car, Ruler, BadgeCheck, Phone } from "lucide-react";

const offices = [
 {title:"Premium Office Building",location:"90 South Street, New Cairo",area:"1,200 sqm",price:"900,000 EGP",parking:"8 Spaces",image:"/images/office-main.jpg",status:"Ready in 60 Days"},
 {title:"Modern Corporate Office",location:"New Cairo Business District",area:"850 sqm",price:"Ask for Price",parking:"6 Spaces",image:"/images/office-main.jpg",status:"Available"},
 {title:"Executive Headquarters",location:"5th Settlement, New Cairo",area:"1,500 sqm",price:"Ask for Price",parking:"12 Spaces",image:"/images/office-main.jpg",status:"Available"},
];
export default function Offices(){return <main><header className="navbar"><div className="container nav-inner"><Link href="/" className="logo"><Image src="/logo.png" alt="Homes" width={80} height={70}/><div><h2>HOMES</h2><p>Real Estate & Commercial</p></div></Link><nav><Link href="/">Home</Link><Link href="/#about">About</Link><Link href="/offices">Offices</Link><Link href="/#contact">Contact</Link></nav><a href="https://wa.me/201223339652" className="nav-btn">Contact Us</a></div></header><section className="listing-hero"><div className="container"><Link href="/" className="back-link"><ArrowLeft size={18}/> Back Home</Link><span className="section-tag">OUR PORTFOLIO</span><h1>Commercial Office Listings</h1><p>Explore premium office spaces and headquarters across Egypt, selected for modern businesses and investors.</p></div></section><section className="listings"><div className="container listing-grid">{offices.map((o,i)=><article className="listing-card" key={i}><div className="listing-image"><Image src={o.image} alt={o.title} width={700} height={500}/><span>{o.status}</span></div><div className="listing-body"><div className="listing-location"><Building2 size={17}/> {o.location}</div><h2>{o.title}</h2><div className="listing-specs"><div><Ruler/><strong>{o.area}</strong><small>Area</small></div><div><Car/><strong>{o.parking}</strong><small>Parking</small></div><div><BadgeCheck/><strong>{o.price}</strong><small>Price</small></div></div><div className="listing-actions"><a href="tel:+201223339652" className="primary-btn"><Phone size={17}/> Call</a><a href="https://wa.me/201223339652" className="secondary-btn dark">WhatsApp</a></div></div></article>)}</div></section><footer className="footer"><div className="container footer-content"><div className="footer-logo"><Image src="/logo.png" alt="Homes" width={60} height={60}/><div><h3>HOMES</h3><p>Real Estate & Commercial</p></div></div><p>© 2026 HOMES Real Estate & Commercial. All Rights Reserved.</p></div></footer></main>}
